app/urls.py
from django.urls import path
from app.views import *

app_name = "app"

urlpatterns = [
    path('', index , name="index"),
    path('more_countries/', view_more_country , name="more_countries"),
    path('contact/', contact , name="contact"),
    path('dashboard/', dashboard , name="dashboard"),
    path('profile/', profile , name="profile"),
    path('upload_documents/', upload_documents , name="upload_documents"),
    path('payment_proof/', payment_proof , name="payment_proof"),
    path('sponsorship_payment_proof/', sponsorship_payment_proof , name="sponsorship_payment_proof"),
    path('about_us/', about_us , name="about_us"),
    path('assessment_form/', assessment_form , name="assessment_form"),
    path('details/<int:country>', detail_page , name="detail_page"),
]

global/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# wrapping language
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.i18n import set_language


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('core.urls')),
    path('', include('app.urls')),
)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/about_us.html
{% extends 'app/assets/admin.html' %}
{% load static %}
{% load i18n %}

{% block title %} {% trans "About Us" %} {% endblock title %}

{% block content %}
<div class="page">


        <!--header start-->
          <!--header start-->
  <header id="masthead" class="header cmt-header-style-01">

        <!-- page-title -->
        <div class="cmt-page-title-row about">
            <div class="cmt-page-title-row-inner">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-12">
                            <div class="page-title-heading">
                                <h2 class="title">About Us</h2>
                            </div>
                            <div class="breadcrumb-wrapper">
                                <span>
                                    <a title="Homepage" href="index.html">Home</a>
                                </span>
                                <span>About Us</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- page-title end -->


    <!--site-main start-->
    <div class="site-main">

        <!--google_map-->
        <div id="google_map" class="google_map res-991-mt-30">
            <div class="map_container" style="height:150px; width:100%;">
            </div>
        </div>


        <!--about-section-->
        <section class="cmt-row about_2-section clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-5 col-5 mr-lg-auto ml-lg-0 offset-3">
                        <div class="cmt-bg cmt-col-bgcolor-yes cmt-bgcolor-grey pt-25 pb-25 pl-25 pr-25 ml-80 res-991-ml-0">
                            <div class="cmt-col-wrapper-bg-layer cmt-bg-layer"></div>
                            <div class="layer-content">
                                <div class="cmt-bgcolor-white pt-60 pb-50 res-991-pt-50 res-991-pb-40">
                                    <div class="col-lg-12">
                                  <div class="ttm_single_image-wrapper ml_110 mr_200 res-575-mr_140">
                                        <img class="img-fluid" src="images/single-img-08.jpg" alt="">
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-12 col-xs-12">
                        <div class="pt-15 pr-30 mb_30 res-991-pr-0 res-991-pt-30">
                            <!-- section title -->
                            <div class="section-title">
                                <div class="title-header">
                                    <h5>{% trans 'who we are' %}</h5>
                                    <h2 class="title">{% trans 'Welcome to' %} <strong> GI GLOBAL IMMIGRATION</strong></h2>
                                </div>
                            </div><!-- section title end -->
                            <p> {% trans 'Welcome to GlobalImmigrationConsults – your trusted partner for worldwide immigration and visa services. We specialize in providing expert guidance and tailored solutions for countries like USA, Canada, Australia, Italy, and beyond. With a focus on excellence and a team of dedicated professionals, we’re here to support you at every step of your immigration journey, including securing your EB-2 NIW visa profile. Let us help you unlock global opportunities with confidence and ease.' %}</p>
                            <div class="pt-10 pr-15 res-991-pr-0">
                                <!-- featured-icon-box -->
                                <div class="featured-icon-box icon-align-before-content style2">
                                    <div class="featured-icon">
                                        <div class="cmt-icon cmt-icon_element-border cmt-icon_element-color-skincolor cmt-icon_element-size-lg cmt-icon_element-style-square">
                                            <i class="flaticon-policy"></i>
                                        </div>
                                    </div>
                                    <div class="featured-content">
                                        <div class="featured-title">
                                            <h5><a href="#">{% trans 'Our Mission' %}</a></h5>
                                        </div>
                                        <div class="featured-desc">
                                            <p style="text-align: justify;">{% trans "Global Immigration Consults is dedicated to providing comprehensive immigration services that simplify the visa application process for our clients. Our mission is to offer expert guidance, personalized support, and timely solutions tailored to each individual’s unique circumstances. We aim to foster a supportive environment where clients feel informed and empowered throughout their immigration journey. Through our commitment to excellence, integrity, and client satisfaction, we strive to build lasting relationships and facilitate successful transitions into new opportunities and communities." %}</p>
                                        </div>
                                    </div>
                                </div><!-- featured-icon-box end -->
                                <!-- featured-icon-box -->
                               <!-- featured-icon-box end -->
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-12 col-lg-12 col-md-12 col-xs-12">
                    <div class="featured-icon-box icon-align-before-content style2">
                                    <div class="featured-icon">
                                        <div class="cmt-icon cmt-icon_element-border cmt-icon_element-color-skincolor cmt-icon_element-size-lg cmt-icon_element-style-square">
                                            <i class="flaticon-contract"></i>
                                        </div>
                                    </div>
                                    <div class="featured-content">
                                        <div class="featured-title">
                                            <h5><a href="#">{% trans "Our Vision" %}</a></h5>
                                        </div>
                                        <div class="featured-desc" >
                                            <p style="text-align: justify;">{% trans "At Global Immigration Consults, our vision is to empower individuals and families to navigate the complexities of immigration with confidence and clarity. We strive to be the leading provider of innovative immigration solutions, ensuring a seamless and positive experience for every client. Our commitment is to uphold integrity, promote cultural diversity, and facilitate global mobility, enabling our clients to build brighter futures in new communities around the world." %}</div>
                                    </div>
                                </div>
                             <div class="section-title">
                                <div class="title-header">
                                    <h4>{% trans "Our Expertise" %}</h4>
                                </div>
                            </div><!-- section title end -->
                            <p>{% trans "Global Immigration Consults specializes in providing tailored immigration solutions backed by extensive knowledge and experience in the field. Our team of seasoned professionals is well-versed in the intricacies of visa regulations, application processes, and immigration policies across various countries. We pride ourselves on our deep understanding of diverse immigration pathways, including work, study, family reunification, and permanent residency options. Our commitment to staying updated on legal developments and industry trends ensures that we deliver accurate, reliable, and effective guidance to our clients. By combining our expertise with a client-centered approach, we empower individuals and families to achieve their immigration goals with confidence and ease." %}</p>
                            <div class="section-title">
                                <div class="title-header">
                                    <h4>{% trans "Our Commitment" %}</h4>
                                </div>
                            </div><!-- section title end -->
                            <p>{% trans "Global Immigration Consults specializes in providing tailored immigration solutions backed by extensive knowledge and experience in the field. Our team of seasoned professionals is well-versed in the intricacies of visa regulations, application processes, and immigration policies across various countries. We pride ourselves on our deep understanding of diverse immigration pathways, including work, study, family reunification, and permanent residency options. Our commitment to staying updated on legal developments and industry trends ensures that we deliver accurate, reliable, and effective guidance to our clients. By combining our expertise with a client-centered approach, we empower individuals and families to achieve their immigration goals with confidence and ease." %}</p>

                            <div class="section-title">
                                <div class="title-header">
                                    <h4>{% trans "Our Services" %}</h4>
                                </div>
                            </div><!-- section title end -->
                            <p>{% trans "With a commitment to excellence and client satisfaction, we empower our clients to achieve their immigration goals and build brighter futures in new communities." %}</p>
                </div><!-- row end -->
            </div>
        </section>
        <!--about-section end-->

    </div><!--site-main end-->


    <!--back-to-top start-->
    <a id="totop" href="#top" style="display: none;">
        <i class="fa fa-angle-up"></i>
    </a>
    <!--back-to-top end-->

</div>

{% endblock %}

templates/app/assessment-documents.html
{% extends 'app/assets/admin.html' %}
{% load static %}
{% load i18n %}

{% block title %} {% trans "Assessment Form" %} {% endblock title %}

{% block content %}
<div class="page">


        <!--header start-->
          <!--header start-->
  <header id="masthead" class="header cmt-header-style-01">

        <!-- page-title -->
        <div class="cmt-page-title-row contact">
            <div class="cmt-page-title-row-inner">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-12">
                            <div class="page-title-heading">
                                <h2 class="title">{% trans 'Assessment Form' %}</h2>
                            </div>
                            <div class="breadcrumb-wrapper">
                                <span>
                                    <a title="Homepage" href="/">{% trans 'Home' %}</a>
                                </span>
                                <span>{% trans 'Assessment Form' %}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- page-title end -->


    <!--site-main start-->
    <div class="site-main">

        <!--google_map-->
        <div id="google_map" class="google_map res-991-mt-30">
            <div class="map_container" style="height:250px; width:100%;">
                <div>
                    {% include 'app/assets/messages.html' %}
                </div>
            </div>
        </div>


        <!--- conatact-section -->
        <section class="cmt-row conatact-section clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="cmt-col-bgcolor-yes cmt-bg cmt-bgcolor-white z-index-2 spacing-7 box-shadow">
                            <div class="cmt-col-wrapper-bg-layer cmt-bg-layer"></div>
                            <div class="row ">
                                <div class="col-lg-4 col-md-5">
                                    <div class="pt-30 pb-30 pl-30 pr-30" style="background: url('{% static 'assets/images/single-img-12.jpg' %}'); height:auto; width:100%; background-size:cover; background-repeat:no-repeat;">
                                        <div class="mb-20">
                                            <h4 style="color:#000; font-weight:bold;">{% trans "Assessment Form" %}</h4>
                                            <p style="background-color: #f5faff; padding:13px; border-radius:10px;">{% trans "This form for Global Immigration Consults is designed to gather essential information from clients seeking visa services. This form helps the company evaluate the client's eligibility for various immigration options, such as work, study, or residency visas. By collecting details about the client's background, qualifications, and specific immigration goals, the form enables the consultants to provide tailored advice and streamline the application process. Overall, it serves as a crucial first step in assisting clients on their journey to successful immigration." %}</p>
                                        </div>

                                    </div>

                                </div>
                                <div class="col-lg-8 col-md-7">
                                    <div class="pl-30 res-991-pl-0 res-767-mt-30">
                                        <!-- section title -->
                                        <div class="section-title with-desc clearfix">
                                            <div class="title-header">
                                                <h5>{% trans "Info needed" %}</h5>
                                                <h2 class="title">{% trans "Upload your" %} <strong>{% trans "Info?" %}</strong></h2>
                                            </div>
                                        </div><!-- section title end -->
                                        <form class="contact_form wrap-form pt-15 clearfix" method="post" novalidate="novalidate">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-6 col-md-6">
                                                    <label>
                                                        {{ form.nationality.label_tag }}
                                                        <span class="text-input">{{ form.nationality }}</span>
                                                    </label>
                                                </div>
                                                <div class="col-lg-6 col-md-6">
                                                    <label>
                                                        {{ form.date_of_birth.label_tag }}
                                                        <span class="text-input"><input type="date" name="date_of_birth"></span>
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-6 col-md-6">
                                                    <label>
                                                        {{ form.passport_number.label_tag }}
                                                        <span class="text-input">{{ form.passport_number }}</span>
                                                    </label>
                                                </div>
                                                <div class="col-lg-6 col-md-6">
                                                    <label>
                                                        {{ form.application_status.label_tag }}
                                                        {% if user.is_staff %}
                                                        <span class="text-input">{{ form.application_status }}</span>
                                                        {% else %}
                                                        <span class="text-input"><input type="text" name="application_status" value="pending" readonly></span>
                                                        {% endif %}
                                                    </label>
                                                </div>
                                                <div class="col-lg-12 col-md-12">
                                                    <label>
                                                        {{ form.visa_type.label_tag }}
                                                        <span class="text-input">{{ form.visa_type }}</span>
                                                    </label>
                                                </div>
                                            </div>



                                            <button class="submit cmt-btn cmt-btn-size-lg cmt-btn-shape-rounded cmt-btn-style-border cmt-btn-color-dark w-100" type="submit" name="submit">{% trans "Upload Documents" %}</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </section>
        <!-- assessment-section end -->

    </div><!--site-main end-->


    <!--back-to-top start-->
    <a id="totop" href="#top" style="display: none;">
        <i class="fa fa-angle-up"></i>
    </a>
    <!--back-to-top end-->

</div>

{% endblock %}

templates/app/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/app/payment_proof.html
{% extends 'app/assets/admin.html' %}
{% load static %}
{% load i18n %}

{% block title %} {% trans "Assessment Form" %} {% endblock title %}



{% block content %}
<div class="page">
        <!--header start-->
          <!--header start-->
  <header id="masthead" class="header cmt-header-style-01">

        <!-- page-title -->
        <div class="cmt-page-title-row contact">
            <div class="cmt-page-title-row-inner">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-12">
                            <div class="page-title-heading">
                                <h2 class="title">{% trans 'Payment Proof' %}</h2>
                            </div>
                            <div class="breadcrumb-wrapper">
                                <span>
                                    <a title="Homepage" href="/">{% trans 'Home' %}</a>
                                </span>
                                <span>{% trans 'Payment Proof' %}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- page-title end -->


    <!--site-main start-->
    <div class="site-main">

        <!--google_map-->
        <div id="google_map" class="google_map res-991-mt-30">
            <div class="map_container" style="height:200px; width:100%;">
                <div>
                    {% include 'app/assets/messages.html' %}
                </div>
            </div>
        </div>


        <!--- conatact-section -->
        <section class="cmt-row conatact-section clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="cmt-col-bgcolor-yes cmt-bg cmt-bgcolor-white z-index-2 spacing-7 box-shadow">
                            <div class="cmt-col-wrapper-bg-layer cmt-bg-layer"></div>
                            <div class="row ">
                                <div class="col-lg-4 col-md-5">
                                    <div class="pt-30 pb-30 pl-30 pr-30" style="background: url('{% static 'assets/images/single-img-12.jpg' %}'); height:auto; width:100%; background-size:cover; background-repeat:no-repeat;">
                                        <div class="mb-20">
                                            <h4 style="color:#000; font-weight:bold;">{% trans "Payment Proof" %}</h4>
                                          </div>

                                    </div>
                                    <div class="mt-3">
                                        <a href="{% url 'app:sponsorship_payment_proof' %}" class="submit cmt-btn text-center cmt-btn-size-lg cmt-btn-shape-rounded cmt-btn-style-border cmt-btn-color-dark w-100">{% trans "Upload Sponsorship Payment " %}</a>
                                    </div>

                                </div>
                                <div class="col-lg-8 col-md-7">
                                    <div class="pl-30 res-991-pl-0 res-767-mt-30">
                                        <!-- section title -->
                                        <div class="section-title with-desc clearfix">
                                            <div class="title-header">
                                                <h5>{% trans "Info needed" %}</h5>
                                                <h2 class="title">{% trans "Upload your" %} <strong>{% trans "Payment Proof" %}</strong></h2>
                                            </div>
                                        </div><!-- section title end -->
                                        <form class="contact_form wrap-form pt-15 clearfix" method="post" novalidate="novalidate"  enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 mb-3">
                                                    <label>
                                                        {{ form.full_payment_image.label_tag }}
                                                        <span class="text-input mt-2">{{ form.full_payment_image }}</span>
                                                        <small>{% trans "submit the reciept of your payment." %}</small>
                                                    </label>
                                                </div>
                                            </div>



                                            <button class="submit cmt-btn cmt-btn-size-lg cmt-btn-shape-rounded cmt-btn-style-border cmt-btn-color-dark w-100" type="submit" name="submit">{% trans "Upload" %}</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </section>
        <!-- assessment-section end -->

    </div><!--site-main end-->


    <!--back-to-top start-->
    <a id="totop" href="#top" style="display: none;">
        <i class="fa fa-angle-up"></i>
    </a>
    <!--back-to-top end-->

</div>

{% endblock %}

templates/app/sponsorship_payment_proof.html
{% extends 'app/assets/admin.html' %}
{% load static %}
{% load i18n %}

{% block title %} {% trans "Assessment Form" %} {% endblock title %}

<style>
    form input[type="image"]{
        padding:10px;
        width:100%;
    }
</style>

{% block content %}
<div class="page">
        <!--header start-->
          <!--header start-->
  <header id="masthead" class="header cmt-header-style-01">

        <!-- page-title -->
        <div class="cmt-page-title-row contact">
            <div class="cmt-page-title-row-inner">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-12">
                            <div class="page-title-heading">
                                <h2 class="title">{% trans 'Sponsorship Payment Proof' %}</h2>
                            </div>
                            <div class="breadcrumb-wrapper">
                                <span>
                                    <a title="Homepage" href="/">{% trans 'Home' %}</a>
                                </span>
                                <span>{% trans 'Sponsorship Payment Proof' %}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- page-title end -->


    <!--site-main start-->
    <div class="site-main">

        <!--google_map-->
        <div id="google_map" class="google_map res-991-mt-30">
            <div class="map_container" style="height:200px; width:100%;">
                <div>
                    {% include 'app/assets/messages.html' %}
                </div>
            </div>
        </div>


        <!--- conatact-section -->
        <section class="cmt-row conatact-section clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="cmt-col-bgcolor-yes cmt-bg cmt-bgcolor-white z-index-2 spacing-7 box-shadow">
                            <div class="cmt-col-wrapper-bg-layer cmt-bg-layer"></div>
                            <div class="row ">
                                <div class="col-lg-4 col-md-5">
                                    <div class="pt-30 pb-30 pl-30 pr-30" style="background: url('{% static 'assets/images/single-img-12.jpg' %}'); height:auto; width:100%; background-size:cover; background-repeat:no-repeat;">
                                        <div class="mb-20">
                                            <h4 style="color:#000; font-weight:bold;">{% trans "Sponsorship Payment Proof" %}</h4>
                                          </div>

                                    </div>
                                    <div class="mt-3">
                                        <a href="{% url 'app:payment_proof' %}" class="submit cmt-btn text-center cmt-btn-size-lg cmt-btn-shape-rounded cmt-btn-style-border cmt-btn-color-dark w-100">{% trans "Upload Payment Proof " %}</a>
                                    </div>

                                </div>
                                <div class="col-lg-8 col-md-7">
                                    <div class="pl-30 res-991-pl-0 res-767-mt-30">
                                        <!-- section title -->
                                        <div class="section-title with-desc clearfix">
                                            <div class="title-header">
                                                <h5>{% trans "Info needed" %}</h5>
                                                <h2 class="title">{% trans "Upload your" %} <strong>{% trans "Sponsorship Payment Proof" %}</strong></h2>
                                            </div>
                                        </div><!-- section title end -->
                                        <form class="contact_form wrap-form pt-15 clearfix" method="post" novalidate="novalidate"  enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 mb-3">
                                                    <label>
                                                        {{ form.sponsorship_payment_image.label_tag }}
                                                        <span class="text-input pt-2">{{ form.sponsorship_payment_image }}</span>
                                                        <small>{% trans "submit the reciept of your payment." %}</small>
                                                    </label>
                                                </div>
                                            </div>



                                            <button class="submit cmt-btn cmt-btn-size-lg cmt-btn-shape-rounded cmt-btn-style-border cmt-btn-color-dark w-100" type="submit" name="submit">{% trans "Upload" %}</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </section>
        <!-- assessment-section end -->

    </div><!--site-main end-->


    <!--back-to-top start-->
    <a id="totop" href="#top" style="display: none;">
        <i class="fa fa-angle-up"></i>
    </a>
    <!--back-to-top end-->

</div>

{% endblock %}