app/urls.py
from django.urls import path
from app.views import *

app_name = "app"

urlpatterns = [
    path('', index , name="index"),
    path('more_countries/', view_more_country , name="more_countries"),
    path('contact/', contact , name="contact"),
    path('dashboard/', dashboard , name="dashboard"),
    path('profile/', profile , name="profile"),
    path('upload_documents/', upload_documents , name="upload_documents"),
    path('payment_proof/', payment_proof , name="payment_proof"),
    path('sponsorship_payment_proof/', sponsorship_payment_proof , name="sponsorship_payment_proof"),
    path('about_us/', about_us , name="about_us"),
    path('assessment_form/', assessment_form , name="assessment_form"),
    path('details/<int:country>', detail_page , name="detail_page"),
]

core/urls.py
from django.urls import path

from core.views import *

app_name = "core"

urlpatterns = [
    path('admin-signup/', admin_signup , name="admin-signup"),
    path('register/', applicant_signup , name="register"),

    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),

    # for social login
    path('login/google/', google_login, name='google_login'),
    path('complete/google/', google_complete, name='google_complete'),
]

global/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# wrapping language
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.i18n import set_language


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('core.urls')),
    path('', include('app.urls')),
)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/assets/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name=”keywords” content="">
    <meta name="description"
        content="At FFA, we take pride in being recognized as one of the top-rated immigration consultancy firms in Dubai, UAE. Our commitment is to offer exceptional services at competitive prices" />
    <meta name="author" content="" />
    <meta name="viewport" content=" width=device-width, initial-scale=1, maximum-scale=1" />
    <title>{% block title %} GIC {% endblock title %} </title>
    <link rel=“canonical” href='' />
    <!-- favicon icon -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
    <!-- bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <!-- animate -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/animate.css' %}" />
    <!-- fontawesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}" />
    <!-- themify -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/themify-icons.css' %}" />
    <!-- flaticon -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/flaticon.css' %}" />
    <!-- slick -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick.css' %}">
    <!-- REVOLUTION LAYERS STYLES -->
    <link rel='stylesheet' id='rs-plugin-settings-css' href="{% static 'assets/revolution/css/rs6.css' %}">
    <!-- prettyphoto -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/prettyPhoto.css' %}">
    <!-- shortcodes -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/shortcodes.css' %}" />
    <!-- main -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}" />
    <!-- main -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/megamenu.css' %}" />
    <!-- responsive -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/responsive.css' %}" />
    <!-- cdn for flags   -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/6.6.6/css/flag-icons.min.css" rel="stylesheet"/>

    <style>
        /* @media only screen and (min-device-width: 668px){
    #slider-1-slide-1-layer-2{
        font-size: 97% !important
    }
    #slider-1-slide-1-layer-1{
        font-size: 76% !important  
    }
} */
    </style>
</head>

<body class="w-100">
    {% include "app/assets/header.html" %}

    {% block content %}


    {% endblock content %}

    {% include "app/assets/footer.html" %}



    <!-- Javascript -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/tether.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easing.js' %}"></script>
    <script src="{% static 'assets/js/jquery-waypoints.js' %}"></script>
    <script src="{% static 'assets/js/jquery-validate.js' %}"></script>
    <script src="{% static 'assets/js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'assets/js/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/numinate.min.js' %}"></script>
    <script src="{% static 'assets/js/imagesloaded.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-isotope.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <!-- Revolution Slider -->
    <script src="{% static 'assets/revolution/js/slider.js' %}"></script>
    <script src="{% static 'assets/revolution/js/revolution.tools.min.js' %}"></script>
    <script src="{% static 'assets/revolution/js/rs6.min.js' %}"></script>
    <!-- Javascript end-->
</body>

</html>

templates/app/assets/footer.html
{% load static %}
{% load i18n %}
<!--footer start-->
<footer class="footer cmt-bgcolor-darkgrey widget-footer clearfix">

    <div class="first-footer">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 widget-area">
                    <div class="widget widget_text mr-25 clearfix">
                        <h3 class="widget-title">{% trans 'About Us' %}</h3>
                        <div class="textwidget widget-text" style="text-align: justify;">
                            <p>{% trans 'At GlobalImmigrationConsults, we distinguish ourselves among immigration consultants in the UAE through our steadfast dedication to delivering exceptional services. As a reliable immigration services provider, we specialize in PR support, work permits, study visas, visit visas, and offer assistance with EB-2 NIW visa profiles.'%}
                            </p>
                        </div>
                        <div class="cmt-horizontal_sep mt-25 mb-30"></div>
                        <div class="social-icons circle">
<!--                            <ul class="list-inline cmt-textcolor-skincolor">-->
<!--                                <li class="social-facebook"><a class="tooltip-top" target="_blank" href="#"-->
<!--                                        data-tooltip="Facebook"><i class="ti ti-facebook"></i></a></li>-->
<!--                                <li class="social-twitter"><a class="tooltip-top" target="_blank" href="#"-->
<!--                                        data-tooltip="twitter"><i class="ti ti-twitter-alt"></i></a></li>-->
<!--                                <li class="social-instagram"><a class="tooltip-top" target="_blank" href="#"-->
<!--                                        data-tooltip="Google"><i class="ti ti-google"></i></a></li>-->
<!--                                <li class="social-twitter"><a class="tooltip-top" target="_blank" href="#"-->
<!--                                        data-tooltip="Linkedin"><i class="ti ti-linkedin"></i></a></li>-->
<!--                            </ul>-->
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 widget-area">
                    <div class="widget widget-recent-post clearfix">
                        <h3 class="widget-title">{% trans 'Immigration and PR Services' %}</h3>
                        <ul id="menu-footer-quick-links">
                            <li><a>{% trans 'Canadian PR' %}</a></li>
                            <li><a>{% trans 'Australia PR' %}</a></li>
                            <li><a>{% trans 'New Zealand PR' %}</a></li>
                            <li><a>{% trans 'United Kingdom Work Permit' %}</a></li>
                            <li><a>{% trans 'Italy Work Permit' %}</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 widget-area">
                    <div class="widget contact_map clearfix">
                        <h3 class="widget-title">{% trans 'Quick contact' %}</h3>
                        <div class="footer_map mb-20">
                            <h2 style="font-weight:bolder; color:#ffa500;">GIC</h2>
                        </div>
                        <ul class="widget_contact_wrapper">
                            <li><i class="cmt-textcolor-skincolor fa fa-map-marker"></i><a href="tel:+971564066883">
                                    +1(510) 546 8996</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="second-footer">
        <div class="container">
            <div class="row no-gutters">
                <div class="widget-area col-xs-12 col-sm-12 col-md-6 col-lg-6">
                    <aside class="widget widget-text">
                        <!--featured-icon-box-->
                        <div class="featured-icon-box icon-align-before-content">
                            <div class="featured-icon">
                                <div
                                    class="cmt-icon cmt-icon_element-fill cmt-icon_element-color-darkgrey cmt-icon_element-size-sm cmt-icon_element-style-square">
                                    <i class="fa fa-envelope-o"></i>
                                </div>
                            </div>
                            <div class="featured-content">
                                <div class="featured-title">
                                    <h5><a href="mailto:canadianmigrant89@gmail.com"
                                            style="text-transform: lowercase;">canadianmigrant89@gmail.com</a></h5>
                                </div>
                                <div class="featured-desc">
                                    <p>{% trans 'Drop Us a Line' %}</p>
                                </div>
                            </div>
                        </div><!-- featured-icon-box end-->
                    </aside>
                </div>
                <div class="widget-area col-xs-12 col-sm-12 col-md-6 col-lg-6">
                    <aside class="widget widget-text cmt-bgcolor-skincolor">
                        <!--featured-icon-box-->
                        <div class="featured-icon-box icon-align-before-content">
                            <div class="featured-icon">
                                <div
                                    class="cmt-icon cmt-icon_element-fill cmt-icon_element-color-darkgrey cmt-icon_element-size-sm cmt-icon_element-style-square">
                                    <i class="fa fa-phone"></i>
                                </div>
                            </div>
                            <div class="featured-content">
                                <div class="featured-title">
                                    <h5><a href="tel:+97143298681">+1(510) 546 8996</a></h5>
                                </div>
                                <div class="featured-desc">
                                    <p>{% trans 'Call Us Now!' %}</p>
                                </div>
                            </div>
                        </div><!-- featured-icon-box end-->
                    </aside>
                </div>

            </div>
        </div>
    </div>
    <div class="bottom-footer-text">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright text-center">
                        <div id="menu-footer-menu">
                            <ul class="footer-nav-menu text-center">
                                <li><a href="/">{% trans 'Home' %}</a></li>
                                <li><a href="#">{% trans 'About' %}</a></li>
                                <li><a href="{% url 'app:more_countries' %}">{% trans 'Blog' %}</a></li>
                                <li><a href="{% url 'app:contact' %}">{% trans 'Contact us' %}</a></li>
                            </ul>
                        </div>
                        <span>Copyright © GlobalImmigrationconsults &nbsp All rights reserved.</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--footer end-->

templates/app/assets/header.html
{% load static %}
{% load i18n %}


<div class="page">
    <!--header start-->
    <header id="masthead" class="header cmt-header-style-01">
        <!-- top_bar -->
        <div class="top_bar cmt-textcolor-black clearfix" style="background-color:#dd901e;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="d-flex flex-row align-items-center justify-content-center">
                            <div class="top_bar_contact_item">
                                <div class="top_bar_icon"><i class="ti ti-alarm-clock"></i></div><span style="color:rgba(90, 11, 77);">{% trans "Monday - Saturday 10.00 A M - 06.00 P M" %}</span>
                            </div>
                            <div class="top_bar_contact_item">
                                <div class="top_bar_icon"></div><span style="color:rgba(90, 11, 77); font-size:1rem; text-align:center; font-weight:bold;">Welcome {{user.username|upper}}!</span>
                            </div>
                            <div class="top_bar_contact_item ml-auto"  >
                                <div class="top_bar_icon"><i class="fa fa-envelope-o"></i></div><a
                                    href="mailto:canadianmigrant89@gmail.com" >canadianmigrant89@gmail.com</a>
                            </div>
                            <div class="cmt-bg cmt-col-bgcolor-yes cmt-right-span cmt-bgcolor-skincolor pl-20">
                                <div class="cmt-col-wrapper-bg-layer cmt-bg-layer"></div>
                                <div class="layer-content">
                                    <div class="top_bar_contact_item">
                                        <div class="top_bar_icon"><i class="fa fa-phone"></i></div><a
                                            href="tel:+1(510) 546 8996"><a href="tel:+1(510) 546 8996">+1(510) 546 8996</a></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- top_bar end-->

        <!-- site-header-menu -->
        <div id="site-header-menu" class="site-header-menu cmt-bgcolor-white">
            <div class="site-header-menu-inner cmt-stickable-header">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <!--site-navigation -->
                            <div class="site-navigation d-flex flex-row align-items-center justify-content-between">
                                <!-- site-branding -->
                                <div class="site-branding ">
                                    <a class="home-link" href="/" title="Tripzia" rel="home">
<!--                                        <img id="logo-img" class="img-center"-->
<!--                                            src="{% static 'assets/images/logo-img.png' %}" alt="logo-img">-->
                                        <h3 class="" style="font-weight:bolder; color:#ffa500;">GIC</h3>
                                    </a>
                                </div><!-- site-branding end -->
                                <!-- widget-info -->
                                <!-- <div class="widget_info mr-auto">
                                <div>Visa & Immigration Consultants</div>
                            </div> -->
                                <div class="d-flex flex-row">
                                    <div class="btn-show-menu-mobile menubar menubar--squeeze" id="menubar--squeeze">
                                        <span class="menubar-box">
                                            <span class="menubar-inner"></span>
                                            <span class="menubar-inner"></span>
                                            <span class="menubar-inner"></span>
                                        </span>
                                    </div>
                                    <!-- menu -->
                                    <nav class="main-menu menu-mobile">
                                        <ul class="menu">
                                            <li>
                                                <a href="/">{% trans 'Home' %}</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'app:about_us' %}">{% trans 'About Us' %}</a>
                                            </li>
                                            <li>
                                                {% if user.is_authenticated %}
                                                <a href="{% url 'app:assessment_form' %}">{% trans 'Assessment form' %}</a>
                                                {% else %}
                                                <a href="{% url 'core:login' %}">{% trans 'Login' %}</a>
                                                {% endif %}
                                            </li>
                                            <li>
                                                <a href="{% url 'app:contact' %}">{% trans 'Contact Us' %}</a>
                                            </li>
                                            <li class="">
                                              <ul class="nav-item dropdown header-profile">
                                                    <form action="{% url 'set_language' %}" method="post">
                                                        {% csrf_token %}
                                                        <input name="next" type="hidden" value="{{ request.get_full_path|slice:"3:" }}">

                                                            <select class="form-select language_dropdown_list" name="language" onchange="this.form.submit()" id="language">
                                                            {% get_current_language as LANGUAGE_CODE %}
                                                            {% get_available_languages as LANGUAGES %}
                                                            {% get_language_info_list for LANGUAGES as languages %}

                                                            {% for language in languages %}
                                                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                                                    <!-- Show the flag and the local language name -->
                                                                    <span class="fi fi-{{ language.code|slice:":2" }}"></span>
                                                                    {{ language.name_local }}
                                                                </option>
                                                            {% endfor %}
                                                        </select>
                                                    </form>
                                              </ul>
                                            </li>
                                            <li>
                                                <a href="{% url 'app:payment_proof' %}">{% trans 'Payment Proof' %}</a>
                                            </li>
                                            <li>
                                                {% if user.is_authenticated %}
                                                <a href="{% url 'core:logout' %}">{% trans 'Logout' %}</a>
                                                {% else %}
                                                {% endif %}
                                            </li>
                                        </ul>
                                    </nav>

                                </div>
                            </div><!-- site-navigation end-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- site-header-menu end-->
    </header>
    <!--header end-->


    <nav class="styled-mobile-menu" id="menu" style="display: none;">
    <ul class="">
        <li ><a href="/">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'app:about_us' %}">{% trans 'About Us' %}</a></li>
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'app:assessment_form' %}">{% trans 'Assessment form' %}</a>
            {% else %}
            <a href="{% url 'core:login' %}">{% trans 'Login' %}</a>
            {% endif %}
        </li>
        <li><a href="{% url 'app:contact' %}">{% trans 'Contact Us' %}</a></li>
        <li>
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
                    <select class="form-select language_dropdown_list" name="language" onchange="this.form.submit()" id="language">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                <span class="fi fi-{{ language.code|slice:':2' }}"></span>
                                {{ language.name_local }}
                            </option>
                        {% endfor %}
                    </select>
                </form>
        </li>
        <li>
            <a href="{% url 'app:payment_proof' %}">{% trans 'Payment Proof' %}</a>
        </li>
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'core:logout' %}">{% trans 'Logout' %}</a>
            {% endif %}
        </li>
    </ul>
    </nav>
</div>

templates/app/assets/messages.html
{% load static %}
{% load i18n %}

{% if messages %}
    <div class="container custom_container mt-3">
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert" style="border-radius:13px;">
              {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

<!--# django-admin compilemessages -l ar-->