app/urls.py
from django.urls import path
from app.views import *

app_name = "app"

urlpatterns = [
    path('', index , name="index"),
    path('more_countries/', view_more_country , name="more_countries"),
    path('contact/', contact , name="contact"),
    path('dashboard/', dashboard , name="dashboard"),
    path('profile/', profile , name="profile"),
    path('upload_documents/', upload_documents , name="upload_documents"),
    path('payment_proof/', payment_proof , name="payment_proof"),
    path('sponsorship_payment_proof/', sponsorship_payment_proof , name="sponsorship_payment_proof"),
    path('about_us/', about_us , name="about_us"),
    path('assessment_form/', assessment_form , name="assessment_form"),
    path('details/<int:country>', detail_page , name="detail_page"),
]

global/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# wrapping language
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.i18n import set_language


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('core.urls')),
    path('', include('app.urls')),
)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/administrator/include/navbar.html
{% load static %}

<div class="container-fluid p-0 m-0 position-relative">
    <div class="row align-items-start g-0">
      
      <div class="col-lg-9 col-xl-10 main-media px-0 position-absolute end-0">
        <!-- nav bar  -->
        <div class="container-fluid sticky-top">
          <div class="row">
            <nav class="navbar navbar-light bg-light">
              <div class="container-fluid">
                <!-- button  -->
                <button
                  class="d-lg-none btn bg-light border-0"
                  type="button"
                  data-bs-toggle="offcanvas"
                  data-bs-target="#offcanvasExample"
                  aria-controls="offcanvasExample"
                >
                  <img
                    id="lightModeImage9"
                    src="../wave-html/assets/icons/menu.svg"
                    alt=""
                    class="menu-icon"
                  />
                  <img
                    id="darkModeImage9"
                    src="../wave-html/assets/icons/menu-dark.svg"
                    alt=""
                    class="menu-icon"
                  />
                </button>
                <!-- button end -->
                <div class="d-none d-md-flex">
                  <p class="m-0 fs-5 w-100">Dashboard</p>
                </div>
                <div class="d-flex gap-3 align-items-center">
                  <div class="d-none d-lg-flex h-25 border rounded-3">
                    <input
                      class="border-0 p-2 rounded-start custom-checkbox custom-background"
                      type="search"
                      placeholder="Search..."
                      name="search"
                      role=""
                    />
                    <button class="border-0 bg-primary rounded-end">
                      <img
                        src="../wave-html/assets/icons/search-header.svg"
                        alt=""
                        class=""
                      />
                    </button>
                  </div>
                  <div
                    class="form-check form-switch custom-form-switch d-flex align-items-center mb-0"
                  >
                    <input
                      class="form-check-input form-check-input-nav custom-checkbox border outline-none"
                      type="checkbox"
                      role="switch"
                      id="flexSwitchCheckChecked"
                      checked
                    />
                  </div>
                  <div class="d-lg-block d-none">
                    <button
                      class="btn btn-nav bg rounded-circle border-0 px-0"
                      type="button"
                      aria-expanded="false"
                    >
                      <img
                        id="lightModeImage"
                        src="../wave-html/assets/icons/bell-header.svg"
                        alt=""
                        class="custom-background border shadow-sm rounded-circle p-2"
                      />
                      <img
                        id="darkModeImage"
                        src="../wave-html/assets/icons/bell-header-dark.svg"
                        alt=""
                        class="custom-background border shadow-sm rounded-circle p-2"
                      />
                    </button>
                  </div>
                  <div class="d-lg-block d-none">
                    <button
                      class="btn btn-nav rounded-circle border-0 px-0"
                      type="button"
                      aria-expanded="false"
                    >
                      <img
                        id="lightModeImage1"
                        src="../wave-html/assets/icons/settings-header.svg"
                        alt=""
                        class="custom-background border shadow-sm rounded-circle p-2"
                      />
                      <img
                        id="darkModeImage1"
                        src="../wave-html/assets/icons/settings-header-dark.svg"
                        alt=""
                        class="custom-background border shadow-sm rounded-circle p-2"
                      />
                    </button>
                  </div>
                  <div class="dropdown d-sm-block d-none">
                    <button
                      class="btn btn-nav dropdown-toggle rounded-circle border-0 px-0"
                      type="button"
                      id="dropdownMenuButton1"
                      data-bs-toggle="dropdown"
                      aria-expanded="false"
                    >
                      <img
                        src="../wave-html/assets/images/Flags.png"
                        alt=""
                        class="custom-background border shadow-sm rounded-circle p-2"
                      />
                      <img
                        id="lightModeImage2"
                        src="../wave-html/assets/icons/angle-down.svg"
                        alt=""
                      />
                      <img
                        id="darkModeImage2"
                        src="../wave-html/assets/icons/angle-down-dark.svg"
                        alt=""
                      />
                    </button>
                    <ul
                      class="dropdown-menu dropdown-menu-end"
                      aria-labelledby="dropdownMenuButton1"
                    >
                      <li>
                        <a class="dropdown-item" href="#"
                          ><img
                            src="../wave-html/assets/images/Flags.png"
                            alt=""
                            class="me-2"
                          /><span>English</span></a
                        >
                      </li>
                      <li>
                        <a class="dropdown-item" href="#"
                          ><img
                            src="{% static 'wave-html/assets/images/Flags-pak.png' %}"
                            alt=""
                            class="me-2"
                          /><span>Urdu</span></a
                        >
                      </li>
                    </ul>
                  </div>
                  <div class="dropdown">
                    <button
                      class="btn btn-nav dropdown-toggle rounded-circle border-0 px-0"
                      type="button"
                      id="dropdownMenuButton1"
                      data-bs-toggle="dropdown"
                      aria-expanded="false"
                    >
                      <img src="../wave-html/assets/images/profile.png" alt="" class="" />
                      <img
                        id="lightModeImage3"
                        src="../wave-html/assets/icons/angle-down.svg"
                        alt=""
                      />
                      <img
                        id="darkModeImage3"
                        src="../wave-html/assets/icons/angle-down-dark.svg"
                        alt=""
                      />
                    </button>
                    <ul
                      class="dropdown-menu dropdown-menu-end"
                      aria-labelledby="dropdownMenuButton1"
                    >
                      <li><a class="dropdown-item" href="#">Profile</a></li>
                      <li>
                        <a class="dropdown-item" href="#">Account Settings</a>
                      </li>
                      <li>
                        <a class="dropdown-item" href="#">Manage Accounts</a>
                      </li>
                      <hr class="m-0" />
                      <li>
                        <a class="dropdown-item" href="#">Notifications</a>
                      </li>
                      <li><a class="dropdown-item" href="#">Settings</a></li>
                      <hr class="m-0" />
                      <li>
                        <a class="dropdown-item" href="../wave-html/sign-in.html"
                          >Sign Out</a
                        >
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </div>
        <!-- navbar end  -->
        
      </div>
    </div>
  </div>

templates/app/administrator/include/sidebar.html
{% load static %}
<!-- sidebar  -->
<div class="offcanvas offcanvas-start w-100" tabindex="-1" id="offcanvasExample"
  aria-labelledby="offcanvasExampleLabel">
  <div class="w-100 sidebar position-relative">
    <div class="mb-4 py-4 d-flex justify-content-center align-items-center sticky-top background-sidebar">
      <img src="../wave-html/assets/images/logo-full.png" alt="" />
      <button type="button"
        class="d-lg-none btn-close p-2 rounded-circle cross-button text-reset position-absolute-cross d-flex justify-content-center align-items-center"
        data-bs-dismiss="offcanvas" aria-label="Close">
        <img src="../wave-html/assets/icons/cross-chats.svg" alt="" />
      </button>
    </div>
    <div class="px-4 d-flex flex-column gap-3">
      <div>
        <h1 class="text-white mb-2 fw-bold text-center bg-warning p-2 rounded-2">GIC</h1>
      </div>
      <!-- dashboard button  -->
      <div class="">
        <a href="{% url 'app:dashboard' %}"
          class="btn text-white d-flex w-100 py-2 px-2 px-0 align-items-center gap-3 {% if request.resolver_match.url_name == 'dashboard' %} active-class {% else %} {% endif %}" type="button"
          aria-haspopup="true" aria-expanded="false">
          <img src="{% static 'wave-html/assets/icons/grid-sidebar.svg' %}" alt="" />
          <p class="m-0 sidebar-media">Dashboard</p>
        </a>
      </div>
      <!-- Profile button  -->
      <div class="accordion" id="accordionExample2">
        <div class="accordion-item accordion-sidebar">
           <a href="{% url 'app:profile' %}" class="text-light">
          <h2 class="accordion-header accordion-sidebar" id="headingthree">
            <button
              class="btn accordion-button accordion-button-dash accordion-sidebar collapsed shadow-none text-white px-2 py-2 d-flex justify-content-between {% if request.resolver_match.url_name == 'profile' %} active-class {% else %} {% endif %}"
              type="button" data-bs-toggle="collapse" data-bs-target="#collapsethree" aria-expanded="false"
              aria-controls="collapsethree">
              <div>
                <img src="../wave-html/assets/icons/user-sidebar.svg" alt="" class="me-2" />
               <span>Profile</span>
              </div>

            </button>
          </h2>
           </a>
        </div>
      </div>

      <!-- process tracking button  -->
      <div class="accordion" id="accordionExample2">
        <div class="accordion-item accordion-sidebar">
          <a href="{% url 'app:upload_documents' %}" class="text-light">
          <h2 class="accordion-header accordion-sidebar" id="headingthree">
            <button
              class="btn accordion-button accordion-button-dash accordion-sidebar collapsed shadow-none text-white px-2 py-2 d-flex justify-content-between {% if request.resolver_match.url_name == 'upload_documents' %} active-class {% else %} {% endif %}"
              type="button" data-bs-toggle="collapse" data-bs-target="#collapsethree" aria-expanded="false"
              aria-controls="collapsethree">
              <div>
                <img src="../wave-html/assets/icons/user-sidebar.svg" alt="" class="me-2" />
                <span>Upload Documents</span>
              </div>

            </button>
          </h2>
          </a>
        </div>
      </div>

    </div>
  </div>
</div>
<!-- sidebar end   -->