app/urls.py
from django.urls import path
from app.views import *

app_name = "app"

urlpatterns = [
    path('', index , name="index"),
    path('more_countries/', view_more_country , name="more_countries"),
    path('contact/', contact , name="contact"),
    path('dashboard/', dashboard , name="dashboard"),
    path('profile/', profile , name="profile"),
    path('upload_documents/', upload_documents , name="upload_documents"),
    path('payment_proof/', payment_proof , name="payment_proof"),
    path('sponsorship_payment_proof/', sponsorship_payment_proof , name="sponsorship_payment_proof"),
    path('about_us/', about_us , name="about_us"),
    path('assessment_form/', assessment_form , name="assessment_form"),
    path('details/<int:country>', detail_page , name="detail_page"),
]

core/urls.py
from django.urls import path

from core.views import *

app_name = "core"

urlpatterns = [
    path('admin-signup/', admin_signup , name="admin-signup"),
    path('register/', applicant_signup , name="register"),

    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),

    # for social login
    path('login/google/', google_login, name='google_login'),
    path('complete/google/', google_complete, name='google_complete'),
]

global/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# wrapping language
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.i18n import set_language


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('core.urls')),
    path('', include('app.urls')),
)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/elements/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %} Global Immigration {% endblock title %}
    </title>
    <link rel="icon" type="image/x-icon" href="{% static './assets/images/favicon_2.png' %} ">
    <link rel="stylesheet" href="{% static './elements/bs/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static './elements/style.css' %}"/>
     {% load static %}
    {% block extra_head %}
    {{ form.media }}
    {% endblock %}
</head>
<body class="w-100">
  {% include "app/elements/header.html" %}

  {% block content %}


  {% endblock content %}



    <script src="{% static './elements/bs/bootstrap.bundle.js' %}"></script>
    <script src="{% static './elements/bs/script.js' %}"></script>
</body>
</html>

templates/app/elements/header.html
{% load static %}
{% load i18n %}

<header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <!--    <a class="navbar-brand fw-bold fs-2" href="#">GIMMIGRATION</a>-->
                <a class="navbar-brand fw-bold fs-2 nav-logo__" href="/">GIC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
                        </li>

                    </ul>
                    <div class="d-flex">
                        {% if user.is_applicant %}
<!--                        <a href="#" class="btn btn-md me-2 register__">Dashboard</a>-->
                        {% elif user.is_staff %}
<!--                        <a href="#" class="btn btn-md me-2 register__">Admin Dashboard</a>-->
<!--                        <a href="{% url 'core:logout' %}" class="btn btn-md me-2 register__purple">logout</a>-->
                        {% else %}
                        <a href="{% url 'core:login' %}" class="btn btn-md me-2 login__">{% trans "Login" %}</a>
                        <a href="{% url 'core:register' %}" class="btn btn-md me-2 register__">{% trans "Register" %}</a>
                        {% endif %}

                        <a class="btn">
                        <form action="{% url 'set_language' %}" method="post" >
                            {% csrf_token %}
                            <input name="next" type="hidden" value="{{ request.get_full_path }}">
                            <select name="language" onchange="this.form.submit()" >
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                        {{ language.name_local }}
                                    </option>
                                {% endfor %}
                            </select>
                        </form>
                        </a>

                    </div>
                </div>
            </div>
        </nav>
    </header>

templates/app/elements/messages.html
{% load static %}
{% load i18n %}

{% if messages %}
    <div class="container custom_container">
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert" style="border-radius:13px;">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" style="border-radius:30%;"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

<!--# django-admin compilemessages -l ar-->